# Generated by Django 5.1.dev20240427013607 on 2024-09-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='recordUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('用户id', models.BigIntegerField()),
                ('用户使用次数', models.BigIntegerField(default=0)),
                ('用户最后使用时间', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
