# Generated by Django 5.1 on 2024-09-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_convertrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertrate',
            name='票价',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
