# Generated by Django 5.1 on 2024-09-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_convertrate_票价'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convertrate',
            old_name='现金',
            new_name='cash',
        ),
        migrations.RenameField(
            model_name='convertrate',
            old_name='航班时间',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='convertrate',
            old_name='票价',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='convertrate',
            name='积分',
        ),
        migrations.AddField(
            model_name='convertrate',
            name='base_fare',
            field=models.BigIntegerField(default=0, verbose_name='base_fare'),
        ),
    ]
